---
- name: Deploy Jenkins
  hosts: jenkins-master
  remote_user: root
  tags: master
  roles:
    - role: jenkins

- name: Configurar Host - Docker
  hosts: jenkins-master
  remote_user: root
  tags: configure
  roles:
    - role: ansible-role-configure-hosts-docker

- name: Install Packages
  hosts: jenkins-master
  remote_user: root
  tags: packages
  roles:
    - role: configure-host